# Generated by Django 5.1.6 on 2025-02-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='color_code',
        ),
        migrations.AddField(
            model_name='marca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marca_imgs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_imgs/'),
        ),
    ]
